---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: install httpd/apache package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd/apache package
    apt:
      name: appache2
      state: latest
    when: ansible_distribution == "Ubuntu"

