---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (OracleLinux)
    tags: always
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
   

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:


  - name: install httpd/apache and php package for OracleLinux
    tags: apache, httpd, OracleLinux
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: install httpd/apache and php package for Ubuntu
    tags: apache, apache2, Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (OracleLinux)
    tags: OracleLinux, mariadb, db
    yum: 
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"
 
  - name: install mariadb package (Ubuntu)
    tags: Ubuntu, mariadb, db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest 

