---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (OracleLinux)
    tags: always
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:


  - name: install httpd/apache and php package for OracleLinux
    tags: apache, httpd, OracleLinux
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: install httpd/apache and php package for Ubuntu
    tags: apache, apache2, Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (OracleLinux)
    tags: OracleLinux, mariadb, db
    yum: 
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"
 
  - name: install mariadb package (Ubuntu)
    tags: Ubuntu, mariadb, db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest 

