- name: add ssh key for AnsibleAuto
  authorized_key:
    user: AnsibleAuto
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMLIk0ZcdnnWI9IQzK6yx6ThTxz1FIRhonIHu5EmyDj Ansible"

- name: openssh | generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
